{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movies-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
spec:
  rules:
  - {{- if .Values.ingress.host }}
    host: {{ .Values.ingress.host }}
    {{- end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: movies-frontend
            port:
              number: {{ .Values.frontend.servicePort }}
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: movies-backend
            port:
              number: {{ .Values.backend.servicePort }}
{{- end }}
